config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :b_lists do
    resources :items
  end

  devise_for :users, controllers: {registrations: 'users/registrations'}

end

app/models/b_list.rb
class BList < ActiveRecord::Base
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :b_list
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/b_lists_controller.rb
class BListsController < ApplicationController
  before_action :b_list, only: [:destroy, :edit, :update, :show]
  def index
    @b_lists = BList.all
  end

  def show
    @items = @b_list.items
  end

  def edit
  end

  def update
    if @b_list.update(b_list_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def new

    @b_list = BList.new
  end

  def create
    @b_list = BList.new(b_list_params)
    if @b_list.save
      redirect_to root_path(@b_list)
    else
      render :new
    end
  end

  def destroy
    @b_list.destroy
    redirect_to root_path
  end



  private
  def b_list
    @b_list = BList.find(params[:id])
  end

  def b_list_params
    params.require(:b_list).permit(:name, :date_created, :date_completed)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @b_lists = BList.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :b_list, only: [:new, :create, :destroy]
  before_action :item, only: [:destroy, :edit, :update, :show]
  def index
    @items = Items.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
    @b_list = BList.find(params[:b_list_id])
  end

  def update
    if @item.update(params[:item].permit(:name, :due_date, :location))
      redirect_to b_list_path(params[:b_list_id])
    else
      render :edit
    end
  end

  def create

    @item = @b_list.items.create(item_params)

    if @item.save
      redirect_to b_list_path(@b_list)
    else
      render :new
    end
  end

  def destroy
    @item.destroy
    redirect_to b_list_path(@b_list)
  end


  private
  def item
    @item = Item.find(params[:id])
  end

  def b_list
    @b_list = BList.find(params[:b_list_id])
  end

  def item_params
    params.require(:item).permit(:name, :due_date, :location)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/b_lists_helper.rb
module BListsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/b_lists/_card.html.erb
<div class="divider"></div>
<div class="row">
 <% b_list.items.each do |item| %>
   <div class="col s12 m4">
     <div class="card small grey text-darken-3">
       <div class="card-content white-text">
         <h5>
           <p>Name: <%= item.name %></p>
           <p>Due Date: <%= item.due_date %></p>
           <p>Location: <%= item.location %></p>
         </h5>
       </div>
       <div class="card-action">
        <%= link_to 'Edit Item', edit_b_list_item_path(b_list, item) %>
        <%= link_to 'Delete Item', b_list_item_path(@b_list, item), method: :delete %>
       </div>
     </div>
   </div>
 <% end %>
</div>

app/views/b_lists/_form.html.erb
<div class="row">
  <%= form_for @b_list do |f| %>
    <div class="input-field col s12">
      <%= f.text_field :name, placeholder: 'Thing To Do'%>
    </div>
    <div class="input-field col s6">
      <%= f.text_field :date_created, placeholder: 'Date Created' %>
    </div>
    <div class="input-field col s6">
      <%= f.text_field :date_completed, placeholder: 'Desired Completion Date' %>
    </div>
    <div class="center-align">
      <%= f.submit class: "waves-effect waves-light grey btn-large" %>
    </div>
  <% end %>
</div>

app/views/b_lists/_formshow.html.erb
<div class="divider"></div>
<div class="row">
 <% b_list.items.each do |item| %>
   <div class="col s12 m4">
     <div class="card small grey text-darken-3">
       <div class="card-content white-text">
         <h5>
           <p>Name: <%= item.name %></p>
           <p>Due Date: <%= item.due_date %></p>
           <p>Location: <%= item.location %></p>
         </h5>
       </div>
       <div class="card-action">
         <%= link_to 'Edit Item', edit_b_list_item_path(b_list, item) %>
         <%= link_to 'Delete Item', b_list_item_path(@b_list, item), method: :delete %>
       </div>
     </div>
   </div>
 <% end %>
</div>

app/views/b_lists/edit.html.erb
<h1>Edit</h1>
<%= render(partial: 'form') %>

app/views/b_lists/index.html.erb
<div class="section">
 <h2 class="grey-text text-lighten-3">Welcome</h2>
 <h5 class="grey-text text-darken-2"><%= current_user.first_name %></h5>
</div>
<% if @b_lists.any?  %>
  <% @b_lists.each do |b_list| %>
    <%= render(partial: 'card', locals: {b_list: b_list}) %>
  <% end %>
<% end %>

app/views/b_lists/new.html.erb
<h1 class="center-align">Create New Bucket</h1>


 <%= render(partial: 'form', locals: {b_list: @b_list}) %>

app/views/b_lists/show.html.erb
<div class="section">
  <div class="container">
    <h2 class="grey-text text-lighten-3"><%= "#{@b_list.name}" %></h2>
    <h5>
      <%= link_to '|  Add Item  |  ', new_b_list_item_path(@b_list) %>
      <%= link_to '|  Edit  |', edit_b_list_path(@b_list) %>
      <%= link_to '|  Delete Bucket  |', b_list_path(@b_list), method: :delete %>
    </h5>
  </div>
</div>
  <%= render(partial: 'card', locals: {b_list: @b_list}) %>

app/views/home/index.html.erb
<div class="section">
  <h2 class="white-text">Welcome</h2>
  <h5><%= current_user.first_name %></h5>
</div>
<div class="divider"></div>

  <% if @b_lists.any? %>
    <div class="row">
      <% @b_lists.each do |b| %>
        <div class="col s12 m4">
          <div class="card small grey darken-3">
            <div class="card-content white-text">
                <h4 class="valign">
                  <%= link_to "#{b.name}", b_list_path(b.id), class: "white-text" %>
                </h4>
            </div>
            <div class="card-action">
              <div class="right">
                <%= form_for b do |f| %>
                  <%= f.check_box :completed %>
                  <%= f.label :completed %>
                <% end %>
              </div>
                <%= link_to "Edit", edit_b_list_path(b) %>
                <%= link_to "Delete", b_list_path(b), method: :delete %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/items/_form.html.erb
<%= form_for [@b_list, @item] do |f| %>
  <%= f.text_field :name, placeholder: 'Name'%>
  <%= f.text_field :due_date, placeholder: 'Due Date' %>
  <%= f.text_field :location, placeholder: 'Location' %>
  <div class="center-align">
    <%= f.submit class: "waves-effect waves-light grey btn-large" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Edit</h1>


<%= render(partial: 'form') %>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class="navbar-fixed">
  <nav class="grey">
    <div class="text-right">
      <div class="brand-logo">
        <%= link_to "Bucket List", root_path %>
      </div>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to 'New Bucket List', new_b_list_path %></li>
        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navwrapper.html.erb
  <nav class="transparent">
    <div class="nav-wrapper">
      <div class="col s12">
        <a href="root_path" class="breadcrumb">Home</a>
        <a href="b_list_path[:id]" class="breadcrumb">Bucket List</a>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BucketList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= yield %>


</body>
</html>